/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.facitec.mec.view.mov;

import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import py.edu.facitec.mec.controller.ClienteController;
import py.edu.facitec.mec.controller.ClienteControllerImpl;
import py.edu.facitec.mec.controller.MantenimientoController;
import py.edu.facitec.mec.controller.MantenimientoControllerImp;
import py.edu.facitec.mec.controller.MantenimientoDetController;
import py.edu.facitec.mec.controller.MantenimientoDetControllerImp;
import py.edu.facitec.mec.controller.ServiciosController;
import py.edu.facitec.mec.controller.ServiciosControllerImp;
import py.edu.facitec.mec.model.Cliente;
import py.edu.facitec.mec.model.Mantenimiento;
import py.edu.facitec.mec.model.MantenimientoDetalle;
import py.edu.facitec.mec.model.Servicio;

/**
 *
 * @author Jorge Fabio
 */
public class FormMovimiento extends javax.swing.JFrame {

    /**
     * Creates new form FormMovimiento
     */
    
    ServiciosController serController;
    ClienteController clieController;
    MantenimientoController cabecera;
    MantenimientoDetController detalle;
    
    static DefaultTableModel modelo;
    
    public FormMovimiento() {
        initComponents();

        modelo = (DefaultTableModel) jTable1.getModel();

        serController = new ServiciosControllerImp();
        clieController = new ClienteControllerImpl();
        cabecera = new MantenimientoControllerImp();
        detalle = new MantenimientoDetControllerImp();
        
        tfMovNro.requestFocus();
        
        Calendar dia = new GregorianCalendar();
        fecha.setCalendar(dia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfMovNro = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        cmbCondicion = new javax.swing.JComboBox<>();
        tfCodClie = new javax.swing.JTextField();
        tfNombClie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tfImpoTotal = new javax.swing.JTextField();
        servCodigo = new javax.swing.JTextField();
        servDescripcion = new javax.swing.JTextField();
        servCantidad = new javax.swing.JTextField();
        servUnitario = new javax.swing.JTextField();
        btnBuscarClie = new javax.swing.JButton();
        btnBuscarSer = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbSituacion = new javax.swing.JComboBox<>();
        btnGrabar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nro. de Movimiento");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Condición:");

        tfMovNro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMovNroFocusLost(evt);
            }
        });
        tfMovNro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMovNroKeyPressed(evt);
            }
        });

        fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaKeyPressed(evt);
            }
        });

        cmbCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));
        cmbCondicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbCondicionKeyPressed(evt);
            }
        });

        tfCodClie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodClieFocusLost(evt);
            }
        });
        tfCodClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodClieKeyPressed(evt);
            }
        });

        tfNombClie.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Servicio", "Cantidad", "P. Unitario", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Importe Total:");

        jLabel6.setText("Observacion:");

        jLabel8.setText("Servicio:");

        jLabel9.setText("Cantidad");

        jLabel10.setText("P. Unitario");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        servCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                servCodigoFocusLost(evt);
            }
        });
        servCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                servCodigoKeyPressed(evt);
            }
        });

        servDescripcion.setEditable(false);

        servCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                servCantidadFocusLost(evt);
            }
        });
        servCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                servCantidadKeyPressed(evt);
            }
        });

        servUnitario.setEditable(false);

        btnBuscarClie.setText("Buscar");
        btnBuscarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClieActionPerformed(evt);
            }
        });
        btnBuscarClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarClieKeyPressed(evt);
            }
        });

        btnBuscarSer.setText("Buscar");
        btnBuscarSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSerActionPerformed(evt);
            }
        });
        btnBuscarSer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarSerKeyPressed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Situacion:");

        cmbSituacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Cancelado" }));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cmbSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnGrabar)
                .addGap(18, 18, 18)
                .addComponent(btnAnular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabar)
                    .addComponent(btnAnular)
                    .addComponent(jButton1)
                    .addComponent(btnSalir))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscarSer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(servCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(servDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(servUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAceptar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBorrar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfImpoTotal))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfMovNro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarClie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodClie, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNombClie, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfMovNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cmbCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCodClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClie))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tfImpoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSer)
                    .addComponent(servDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar)
                    .addComponent(btnBorrar))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnBuscarSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSerActionPerformed
        FormServiciosConsulta cons = new FormServiciosConsulta(this, rootPaneCheckingEnabled);
        servCodigo.requestFocus();
        cons.setVisible(true);
    }//GEN-LAST:event_btnBuscarSerActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if(servCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el codigo de un servicio", "Aviso", 1);
            servCodigo.requestFocus();
        }else{
            cargarTabla(); sumarColumnasTabla(); limpiarCamposServicioDetalle();            
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void servCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_servCodigoFocusLost
        if (servCodigo.getText().isEmpty()) {
            
        }else{
            obtenerServicios();
        }
    }//GEN-LAST:event_servCodigoFocusLost

    private void btnBuscarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClieActionPerformed
        FormClienteConsulta consulta = new FormClienteConsulta(this, rootPaneCheckingEnabled);
        consulta.setVisible(true);
    }//GEN-LAST:event_btnBuscarClieActionPerformed

    private void tfCodClieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodClieFocusLost
        Cliente clie = clieController.recuperarPorCodigo(Integer.parseInt(tfCodClie.getText()));
        if (clie!=null) {
            tfNombClie.setText(clie.getNombres()+" "+clie.getApellidos());            
        }else{
            JOptionPane.showMessageDialog(this, "No existe este cliente", "Aviso", 1);
            tfCodClie.requestFocus();
            tfCodClie.setText("");
        }
    }//GEN-LAST:event_tfCodClieFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfMovNroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMovNroKeyPressed
        moverConEnter(evt, fecha);
    }//GEN-LAST:event_tfMovNroKeyPressed

    private void fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaKeyPressed
        moverConEnter(evt, cmbCondicion);
    }//GEN-LAST:event_fechaKeyPressed

    private void cmbCondicionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCondicionKeyPressed
        moverConEnter(evt, btnBuscarClie);
    }//GEN-LAST:event_cmbCondicionKeyPressed

    private void btnBuscarClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarClieKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClieKeyPressed

    private void tfCodClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodClieKeyPressed
        moverConEnter(evt, btnBuscarSer);
    }//GEN-LAST:event_tfCodClieKeyPressed

    private void btnBuscarSerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarSerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarSerKeyPressed

    private void servCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_servCodigoKeyPressed
        moverConEnter(evt, servCantidad);
    }//GEN-LAST:event_servCodigoKeyPressed

    private void servCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_servCantidadKeyPressed
        moverConEnter(evt, btnAceptar);
    }//GEN-LAST:event_servCantidadKeyPressed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        guardarMantenimiento();
        guardarDetalle();
        limpiar();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tfMovNroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMovNroFocusLost
        if(tfMovNro.getText().isEmpty()){
            tfMovNro.setText(cabecera.obtenerMaximo()+"");
        }else{
            obtenerMovimiento();
            fecha.requestFocus();
        }
    }//GEN-LAST:event_tfMovNroFocusLost

    private void servCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_servCantidadFocusLost
        if (servCantidad.getText().isEmpty()) {
            servCantidad.setText("1");
        }
    }//GEN-LAST:event_servCantidadFocusLost

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        eliminarFila();
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMovimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscarClie;
    private javax.swing.JButton btnBuscarSer;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbCondicion;
    private javax.swing.JComboBox<String> cmbSituacion;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField servCantidad;
    public static javax.swing.JTextField servCodigo;
    private javax.swing.JTextField servDescripcion;
    private javax.swing.JTextField servUnitario;
    public static javax.swing.JTextField tfCodClie;
    private javax.swing.JTextField tfImpoTotal;
    private javax.swing.JTextField tfMovNro;
    private javax.swing.JTextField tfNombClie;
    // End of variables declaration//GEN-END:variables

    private void obtenerServicios() {
        Servicio ser = new Servicio();
        ser = serController.recuperarPorCodigo(Integer.parseInt(servCodigo.getText()));
        if(ser!=null){
            servDescripcion.setText(ser.getDescripcion());
            servUnitario.setText(ser.getValor_unitario()+"");
        }else{
            JOptionPane.showMessageDialog(this, "No existe este serivcio", "Aviso", 1);
            servCodigo.setText("");
            servCodigo.requestFocus();
        }
        
        
    }

    private void limpiarCamposServicioDetalle() { // Limpia los campos donde se cargan los servicios
        servCodigo.requestFocus();
        servCodigo.setText("");
        servDescripcion.setText("");
        servCantidad.setText("");
        servUnitario.setText("");
    }

    private void limpiar() {
        
        tfMovNro.requestFocus();
        tfMovNro.setText("");
        cmbCondicion.setSelectedIndex(0);
        tfCodClie.setText("");
        tfNombClie.setText("");
        tfImpoTotal.setText("");
        servCodigo.setText("");
        servDescripcion.setText("");
        servCantidad.setText("");
        servUnitario.setText("");
        
        //ciclo para limpiar la tabla
        for (int i = 0; i < jTable1.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
    }
    
    private void moverConEnter(java.awt.event.KeyEvent evt, JComponent source) {
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            source.requestFocus();
        }
    }

    private void guardarDetalle() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            MantenimientoDetalle det = new MantenimientoDetalle();
            det.setMant_codigo(Integer.parseInt(tfMovNro.getText()));
            det.setServ_codigo(Integer.parseInt(jTable1.getValueAt(i, 0).toString()));
            det.setCantidad(Double.parseDouble(jTable1.getValueAt(i, 2).toString()));
            det.setPrecio(Double.parseDouble(jTable1.getValueAt(i, 3).toString()));
            det.setSubtotal(Double.parseDouble(jTable1.getValueAt(i, 4).toString()));
            detalle.registrar(det);
            
        }
    }

    private void guardarMantenimiento() {
        Mantenimiento mant = new Mantenimiento(
                fecha.getDate(), 
                Integer.parseInt(tfCodClie.getText()), 
                cmbCondicion.getSelectedItem().toString(), 
                Double.parseDouble(tfImpoTotal.getText()), 
                jTextArea1.getText(), 
                cmbSituacion.getSelectedItem().toString());
        cabecera.registrar(mant);
    }

    private void sumarColumnasTabla() {
        
        double sumatoria1=0.0;

        int totalRow= jTable1.getRowCount();

        totalRow-=1;

        for(int i=0;i<=(totalRow);i++){
            
            double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,4)));
//en la parte de arriba indica el primer parametro la fila y el segundo la columna la cual estaras //manejando

            sumatoria1+=sumatoria;
            
            tfImpoTotal.setText(sumatoria1+"");
        }
    }

    private void cargarTabla() {
        
        Object [] fila=new Object[5];

        fila[0]=servCodigo.getText();
        fila[1]=servDescripcion.getText();
        fila[2]=servCantidad.getText();
        fila[3]=servUnitario.getText();
        Double can, uni, subtot;
        can = Double.parseDouble(servCantidad.getText());
        uni = Double.parseDouble(servUnitario.getText());
        subtot = can*uni;
        fila[4]=subtot;
        
        modelo.addRow(fila);

        jTable1.setModel(modelo);
    }

    private void eliminarFila() {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getSelectedRow();
        if (a<0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla" );
        }else {
            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea Eliminar el registro? ");
            if(JOptionPane.OK_OPTION==confirmar) {
                model.removeRow(a);
            }
        }
    }

    private void obtenerMovimiento() {
        
        Mantenimiento mant = cabecera.recuperarPorCodigo(Integer.parseInt(tfMovNro.getText()));
        fecha.setDate(mant.getFecha());
        cmbCondicion.setSelectedItem(mant.getCondicion());
        tfCodClie.setText(mant.getCodigo()+"");
//        
//        List<MantenimientoDetalle> mantDet = detalle.recuperarPorFiltro(Integer.parseInt(tfMovNro.getText()));
//        
//        for (int i = 0; i < mantDet.size(); i++) {
//            
//            Servicio ser = serController.recuperarPorCodigo(mantDet.get(i).getServ_codigo());
//            
//            Object [] fila = new Object[5];
//            fila[0]=mantDet.get(i).getServ_codigo();
//            fila[1]=ser.getNombre();
//            fila[2]=mantDet.get(i).getCantidad();
//            fila[3]=mantDet.get(i).getPrecio();
//            Double can, uni, subtot;
//            can = Double.parseDouble(servCantidad.getText());
//            uni = Double.parseDouble(servUnitario.getText());
//            subtot = can*uni;
//            fila[4]=subtot;
//            
//            modelo.addRow(fila);
//            
//            jTable1.setModel(modelo);
        
//        }
    }
}
